<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReverseProxy.Domain\ReverseProxy.Domain.csproj" />
    <ProjectReference Include="..\ReverseProxy.Application\ReverseProxy.Application.csproj" />
    <ProjectReference Include="..\ReverseProxy.Infrastructure\ReverseProxy.Infrastructure.csproj" />
  </ItemGroup>

</Project>